# Generated by Django 4.0.2 on 2022-11-09 13:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200)),
                ('nickName', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('info', models.CharField(blank=True, max_length=30, null=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(blank=True, max_length=256, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.IntegerField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, default='India', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Landline', 'LandLine'), ('Mobile', 'Mobile'), ('Fax', 'Fax')], max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='additionalWorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workType', models.CharField(blank=True, choices=[('job', 'Job'), ('business', 'Business')], max_length=50, null=True)),
                ('workEmailAddress', models.EmailField(blank=True, max_length=200, null=True)),
                ('workAddress', models.CharField(blank=True, max_length=256, null=True)),
                ('workCity', models.CharField(blank=True, max_length=200, null=True)),
                ('workPostalCode', models.IntegerField(blank=True, null=True)),
                ('workState', models.CharField(blank=True, max_length=200, null=True)),
                ('workCountry', models.CharField(blank=True, default='India', max_length=200, null=True)),
                ('workWebsite', models.CharField(blank=True, max_length=200, null=True)),
                ('workMobile', models.IntegerField(blank=True, null=True)),
                ('workPhone', models.IntegerField(blank=True, null=True)),
                ('workFax', models.IntegerField(blank=True, null=True)),
                ('workCompany', models.CharField(blank=True, max_length=200, null=True)),
                ('workJobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
