# Generated by Django 4.0.2 on 2022-11-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='additionalWorkInfo',
        ),
    ]
